### PR TITLE
lab 2

### PR DESCRIPTION
**Pull request by explosion204**
main repo: https://github.com/explosion204/tabata-timer

### CODE REVIEW

**Comment by explosion204** [comment]
Just to be clear, lab1 pushed directly to main branch because it was reviewed IRL. I will continue using separate repos for every project and updating the pull requests from time to time (lab3 progress is landing here in 4-5 days, I suppose)

**Comment by gmltA** [comment]
Just make sure to create PR for the second project before merge.

**Comment by explosion204** [comment]
> Just make sure to create PR for the second project before merge.
Does that mean I must make another one PR for lab1 even if we're done with it more than two month ago? Anyway, I'm waiting for your suggestions about the second lab! =)

**Comment by gmltA** [comment]
> Does that mean I must make another one PR for lab1 even if we're done with it more than two month ago? Anyway, I'm waiting for your suggestions about the second lab! =)

No need to do that for the first one.

**Comment by explosion204** [comment]
screenshots: 
https://drive.google.com/drive/folders/1mmAhIwPa1q8Yvmac9gADvPI2kMuS6EMU?usp=sharing

**Review by gmltA — APPROVED** [review]
Looks good.

**Pull request merged**
